### ISSUE TITLE
Clarification on CASIA-B test sequences

### ISSUE THREAD

**Issue by mjmarin** [ChaoFan96/GaitPart#10]
Dear authors, first of all, congratulations on your great work.
Reviewing your results on CASIA-B, using 50 subjects for testing (Section 4.1), we wonder what are the exact video sequences that are not included in the actual test. I mean, if per scenario and camera, 2 sequences are used per subject for testing, this makes a total of 100 sequences. Therefore, any number of correctly classified sequences reported as a percentage cannot have decimal numbers, e.g. Table 3, scenario CL #1-2, [GaitPart(ours)](https://openaccess.thecvf.com/content_CVPR_2020/papers/Fan_GaitPart_Temporal_Part-Based_Model_for_Gait_Recognition_CVPR_2020_paper.pdf) --> 70.7 (if you correctly predict 70 out of 100 sequences, that's 70.0). Same with all remaining results in the table. 
Apologies in advance if this is a naive question and the answer is written somewhere else.
Thank you very much.

**Comment by mjmarin** [comment]
We have solved our doubt. 
Closing this issue.

**Comment by ChaoFan96** [comment]
Hi, the OpenGait is released now! ( https://github.com/ShiqiYu/OpenGait )
This project not only contains the full code of gaitpart but also reproduces several SOTA models of gait recognition.
Enjoy it and any questions or suggestions are welcome!
