### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by zhuduowang** [ChaoFan96/GaitPart#2]
Dear author! I want to know when the code is available?

**Comment by ChaoFan96** [comment]
Thanks for your patience, refer to [here](https://github.com/ChaoFan96/GaitPart/issues/1), please.

**Comment by ChaoFan96** [comment]
Hi, the OpenGait is released now! ( https://github.com/ShiqiYu/OpenGait )
This project not only contains the full code of gaitpart but also reproduces several SOTA models of gait recognition.
Enjoy it and any questions or suggestions are welcome!
