### ISSUE TITLE
Some questions about Maxpooling layers and Leakly Relu activations

### ISSUE THREAD

**Issue by weixming** [ChaoFan96/GaitPart#4]
In Section 3.4, where are Maxpooling layers and Leakly Relu activations placed? Which floor is behind?

**Comment by ChaoFan96** [comment]
Thanks for your inquery!
FConv -> Leakly ReLu -> Max Pooling
Refer to Table.1 for more network details, please!
Hope this respond would be helpful for you!

**Comment by weixming** [comment]
Thank you! How to calculate the distance between feature vectors during training?

**Comment by ChaoFan96** [comment]
Hi, the OpenGait is released now! ( https://github.com/ShiqiYu/OpenGait )
This project not only contains the full code of gaitpart but also reproduces several SOTA models of gait recognition.
Enjoy it and any questions or suggestions are welcome!
