### ISSUE TITLE
about Sampler

### ISSUE THREAD

**Issue by ShinanZou** [ChaoFan96/GaitPart#7]
Hello, there are some questions about Sampler.I have read your paper, and I want to know whether the data larger than 40 frames can be intercepted from 40 frames, and then 30 frames can be extracted without putting back, and sorted;30 to 40 frames of data directly without putting back 30 frames are extracted for sorting;Data less than 30 frames and more than 14 frames are collected first, and then the missing frames are randomly selected and combined into 30 frames and sorted.

**Comment by ChaoFan96** [comment]
Thanks for your attention.
But I'm Sorry... I can not get your question from your description.
你能用中文描述一下吗？

**Comment by ShinanZou** [comment]
你好，有一些疑问关于Sampler。我读了你们的论文，我想知道是不是大于40帧的数据就截取40帧出来，然后不放回的抽取30帧，并排序；30到40帧的数据直接不放回的抽取30帧出来排序；小于30帧大于14帧的数据，首先全部收集，然后再随机抽取出缺少的帧数，组合成30帧并排序。

**Comment by ChaoFan96** [comment]
是的呢。

**Comment by ShinanZou** [comment]
感谢你的回答。然后，那抽取（p，k）大小的batch_size的方式是像gaitset那样吗？

**Comment by ChaoFan96** [comment]
你好，这些实现细节均在Sec3.4中有所提及，欢迎提交有关复现却未在文中说明的问题。

**Comment by ChaoFan96** [comment]
Hi, the OpenGait is released now! ( https://github.com/ShiqiYu/OpenGait )
This project not only contains the full code of gaitpart but also reproduces several SOTA models of gait recognition.
Enjoy it and any questions or suggestions are welcome!
